### ISSUE TITLE
Detuned sounds

### ISSUE THREAD

**Issue by puresoul** [knaggsy2000/REAPER-JSFX-KaossilatorProPlus#1]
Hi,

just simple question, when i set kaossilator on off/full, the sounds/tones is disharmonic, sounds worse than pianino without tunning for 8y. 

Is there some possible workaround?

Thanks for reply

**Comment by knaggsy2000** [comment]
Sorry for the delay in replying.

I do remember this happening when I developed with the device but since it was quite a few years ago, I can't remember what the actual issue was :/  and I haven't even touched that hardware in quite a few years.

But I do kinda remember that the kaoss should be set to a certain key to match the key of source project invoking it.  As that is the prime reason for things being disharmonic.

**Comment by puresoul** [comment]
Only almost usable way for me was limit koss to 3 octaves and then do some stupid math to adress midi notes to CC. It's very ugly hack, but only way for me to get right tones from that hell of machine. I just hate korg because of this machine :-D

**Comment by knaggsy2000** [comment]
I originally only wrote this plugin so I could use the kaoss pad for some of my uni projects.  What math was you doing for it?  As I thought my plugin did most things.  But can't confirm as it was a few years ago.

What are you trying to get from it?  As if needed, I will pull out that hardware and re-test things.  I would like to help a fellow Kaoss pad user.

**Comment by knaggsy2000** [comment]
"Don't forget to set the note range on your KP+ to FULL and the key scale to OFF" - hmmm, maybe something else is off?

What is your environment?  Like OS, DAW, etc?

**Comment by puresoul** [comment]
This is the cause of my problems, if set to full/off, the plugin works fine, but notes coming from kp are detuned (if i try some note on any other synth and same note on kp, the tunning is off). Using Reaper on Windows 11

**Comment by knaggsy2000** [comment]
I remember something like this happened to be before during the development of that plugin, but that was a few years ago and I can't remember what the actually issue was.

Can you provide actual details on how to reproduce this?  As in: -

1. REAPER version
2. KP settings
3. etc

And what you expect for the results?


Are you aware that in REAPER that you can set the key of music?  Just worth me mentioning,
